# Generated by Django 4.2.7 on 2023-11-14 19:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webhook_tester', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headers', models.JSONField()),
                ('query', models.JSONField()),
                ('payload', models.JSONField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webhook_tester.workspace')),
            ],
        ),
    ]
